// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiF3mLAryGQYIUl_0IP6WTa25egrNlVkE',
    appId: '1:786622160093:web:731c06bfe06710f96b0f34',
    messagingSenderId: '786622160093',
    projectId: 'meetreminder-11879',
    authDomain: 'meetreminder-11879.firebaseapp.com',
    storageBucket: 'meetreminder-11879.firebasestorage.app',
    measurementId: 'G-93PYPTTHPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzIYfSwPJGjfbvcg87oQsSsHxyChBaM1k',
    appId: '1:786622160093:android:806df1d6c068d6da6b0f34',
    messagingSenderId: '786622160093',
    projectId: 'meetreminder-11879',
    storageBucket: 'meetreminder-11879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYL854QZJ4wwbTaa_84rYWPSoQzrd9EfE',
    appId: '1:786622160093:ios:43fb506116d26d0e6b0f34',
    messagingSenderId: '786622160093',
    projectId: 'meetreminder-11879',
    storageBucket: 'meetreminder-11879.firebasestorage.app',
    iosBundleId: 'com.example.meetreminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYL854QZJ4wwbTaa_84rYWPSoQzrd9EfE',
    appId: '1:786622160093:ios:43fb506116d26d0e6b0f34',
    messagingSenderId: '786622160093',
    projectId: 'meetreminder-11879',
    storageBucket: 'meetreminder-11879.firebasestorage.app',
    iosBundleId: 'com.example.meetreminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiF3mLAryGQYIUl_0IP6WTa25egrNlVkE',
    appId: '1:786622160093:web:0b1a24ba2af5c6916b0f34',
    messagingSenderId: '786622160093',
    projectId: 'meetreminder-11879',
    authDomain: 'meetreminder-11879.firebaseapp.com',
    storageBucket: 'meetreminder-11879.firebasestorage.app',
    measurementId: 'G-EFP0ECGPF7',
  );
}
